var api_8h =
[
    [ "ITimeSeriesOfPoints", "classshyft_1_1api_1_1_i_time_series_of_points.html", "classshyft_1_1api_1_1_i_time_series_of_points" ],
    [ "GenericTs", "structshyft_1_1api_1_1_generic_ts.html", "structshyft_1_1api_1_1_generic_ts" ],
    [ "TsFactory", "structshyft_1_1api_1_1_ts_factory.html", "structshyft_1_1api_1_1_ts_factory" ],
    [ "GeoPointSource", "classshyft_1_1api_1_1_geo_point_source.html", "classshyft_1_1api_1_1_geo_point_source" ],
    [ "TemperatureSource", "structshyft_1_1api_1_1_temperature_source.html", "structshyft_1_1api_1_1_temperature_source" ],
    [ "PrecipitationSource", "structshyft_1_1api_1_1_precipitation_source.html", "structshyft_1_1api_1_1_precipitation_source" ],
    [ "WindSpeedSource", "structshyft_1_1api_1_1_wind_speed_source.html", "structshyft_1_1api_1_1_wind_speed_source" ],
    [ "RelHumSource", "structshyft_1_1api_1_1_rel_hum_source.html", "structshyft_1_1api_1_1_rel_hum_source" ],
    [ "RadiationSource", "structshyft_1_1api_1_1_radiation_source.html", "structshyft_1_1api_1_1_radiation_source" ],
    [ "a_region_environment", "structshyft_1_1api_1_1a__region__environment.html", "structshyft_1_1api_1_1a__region__environment" ],
    [ "basic_cell_statistics", "structshyft_1_1api_1_1basic__cell__statistics.html", "structshyft_1_1api_1_1basic__cell__statistics" ],
    [ "kirchner_cell_state_statistics", "structshyft_1_1api_1_1kirchner__cell__state__statistics.html", "structshyft_1_1api_1_1kirchner__cell__state__statistics" ],
    [ "gamma_snow_cell_state_statistics", "structshyft_1_1api_1_1gamma__snow__cell__state__statistics.html", "structshyft_1_1api_1_1gamma__snow__cell__state__statistics" ],
    [ "gamma_snow_cell_response_statistics", "structshyft_1_1api_1_1gamma__snow__cell__response__statistics.html", "structshyft_1_1api_1_1gamma__snow__cell__response__statistics" ],
    [ "skaugen_cell_state_statistics", "structshyft_1_1api_1_1skaugen__cell__state__statistics.html", "structshyft_1_1api_1_1skaugen__cell__state__statistics" ],
    [ "skaugen_cell_response_statistics", "structshyft_1_1api_1_1skaugen__cell__response__statistics.html", "structshyft_1_1api_1_1skaugen__cell__response__statistics" ],
    [ "priestley_taylor_cell_response_statistics", "structshyft_1_1api_1_1priestley__taylor__cell__response__statistics.html", "structshyft_1_1api_1_1priestley__taylor__cell__response__statistics" ],
    [ "actual_evapotranspiration_cell_response_statistics", "structshyft_1_1api_1_1actual__evapotranspiration__cell__response__statistics.html", "structshyft_1_1api_1_1actual__evapotranspiration__cell__response__statistics" ],
    [ "_USE_MATH_DEFINES", "api_8h.html#a525335710b53cb064ca56b936120431e", null ],
    [ "ITimeSeriesOfPoints_", "api_8h.html#a69dabafe764f4e061f37728525f8cde1", null ],
    [ "result_ts_t", "api_8h.html#acf09b4ef98e3f7f9c0da00bc0990a4d5", null ],
    [ "result_ts_t_", "api_8h.html#afcfaa9026650adacd25625447f417b99", null ]
];