var hierarchy =
[
    [ "shyft::api::a_region_environment", "structshyft_1_1api_1_1a__region__environment.html", null ],
    [ "shyft::api::actual_evapotranspiration_cell_response_statistics< cell >", "structshyft_1_1api_1_1actual__evapotranspiration__cell__response__statistics.html", null ],
    [ "shyft::core::pt_hs_k::all_response_collector", "structshyft_1_1core_1_1pt__hs__k_1_1all__response__collector.html", null ],
    [ "shyft::core::pt_ss_k::all_response_collector", "structshyft_1_1core_1_1pt__ss__k_1_1all__response__collector.html", null ],
    [ "shyft::core::pt_gs_k::all_response_collector", "structshyft_1_1core_1_1pt__gs__k_1_1all__response__collector.html", null ],
    [ "shyft::timeseries::average_accessor< S, TA >", "classshyft_1_1timeseries_1_1average__accessor.html", null ],
    [ "shyft::api::basic_cell_statistics< cell >", "structshyft_1_1api_1_1basic__cell__statistics.html", null ],
    [ "shyft::core::gamma_snow::calculator< P, S, R >", "classshyft_1_1core_1_1gamma__snow_1_1calculator.html", null ],
    [ "shyft::core::priestley_taylor::calculator", "structshyft_1_1core_1_1priestley__taylor_1_1calculator.html", null ],
    [ "shyft::core::hbv_snow::calculator< P, S >", "structshyft_1_1core_1_1hbv__snow_1_1calculator.html", null ],
    [ "shyft::core::precipitation_correction::calculator", "structshyft_1_1core_1_1precipitation__correction_1_1calculator.html", null ],
    [ "shyft::core::kirchner::calculator< AC, P >", "classshyft_1_1core_1_1kirchner_1_1calculator.html", null ],
    [ "shyft::core::skaugen::calculator< P, S, R >", "classshyft_1_1core_1_1skaugen_1_1calculator.html", null ],
    [ "shyft::core::calendar", "structshyft_1_1core_1_1calendar.html", null ],
    [ "shyft::core::cell< P, E, S, SC, RC >", "structshyft_1_1core_1_1cell.html", null ],
    [ "shyft::experimental::repository::cell_file_repository< C >", "classshyft_1_1experimental_1_1repository_1_1cell__file__repository.html", null ],
    [ "shyft::core::cell_statistics", "structshyft_1_1core_1_1cell__statistics.html", null ],
    [ "shyft::core::kirchner::composite_trapezoidal_average< S >", "classshyft_1_1core_1_1kirchner_1_1composite__trapezoidal__average.html", null ],
    [ "shyft::core::bayesian_kriging::const_parameter", "classshyft_1_1core_1_1bayesian__kriging_1_1const__parameter.html", null ],
    [ "shyft::timeseries::constant_timeseries< TA >", "classshyft_1_1timeseries_1_1constant__timeseries.html", null ],
    [ "shyft::timeseries::direct_accessor< S, TA >", "classshyft_1_1timeseries_1_1direct__accessor.html", null ],
    [ "shyft::timeseries::direct_accessor< constant_timeseries< TA >, TA >", "classshyft_1_1timeseries_1_1direct__accessor_3_01constant__timeseries_3_01_t_a_01_4_00_01_t_a_01_4.html", null ],
    [ "shyft::timeseries::direct_accessor< point_timeseries< TA >, TA >", "classshyft_1_1timeseries_1_1direct__accessor_3_01point__timeseries_3_01_t_a_01_4_00_01_t_a_01_4.html", null ],
    [ "shyft::core::pt_gs_k::discharge_collector", "structshyft_1_1core_1_1pt__gs__k_1_1discharge__collector.html", null ],
    [ "shyft::core::pt_hs_k::discharge_collector", "structshyft_1_1core_1_1pt__hs__k_1_1discharge__collector.html", null ],
    [ "shyft::core::pt_ss_k::discharge_collector", "structshyft_1_1core_1_1pt__ss__k_1_1discharge__collector.html", null ],
    [ "shyft::core::optimizer::dream", "classshyft_1_1core_1_1optimizer_1_1dream.html", null ],
    [ "shyft::experimental::dtm", "structshyft_1_1experimental_1_1dtm.html", null ],
    [ "shyft::core::environment< timeaxis, temperature_ts, precipitation_ts, radiation_ts, relhum_ts, windspeed_ts >", "structshyft_1_1core_1_1environment.html", null ],
    [ "exception", null, [
      [ "shyft::core::grf::semivariogram_error", "classshyft_1_1core_1_1grf_1_1semivariogram__error.html", null ],
      [ "shyft::core::skaugen::mass_balance_error", "classshyft_1_1core_1_1skaugen_1_1mass__balance__error.html", null ]
    ] ],
    [ "shyft::core::grf::exponential_model", "structshyft_1_1core_1_1grf_1_1exponential__model.html", null ],
    [ "shyft::timeseries::function_timeseries< TA, F >", "classshyft_1_1timeseries_1_1function__timeseries.html", null ],
    [ "shyft::api::gamma_snow_cell_response_statistics< cell >", "structshyft_1_1api_1_1gamma__snow__cell__response__statistics.html", null ],
    [ "shyft::api::gamma_snow_cell_state_statistics< cell >", "structshyft_1_1api_1_1gamma__snow__cell__state__statistics.html", null ],
    [ "shyft::core::grf::gaussian_model", "structshyft_1_1core_1_1grf_1_1gaussian__model.html", null ],
    [ "shyft::core::geo_cell_data", "structshyft_1_1core_1_1geo__cell__data.html", null ],
    [ "shyft::experimental::geo_cell_data_computer", "classshyft_1_1experimental_1_1geo__cell__data__computer.html", null ],
    [ "shyft::experimental::repository::geo_located_ts_file_repository", "classshyft_1_1experimental_1_1repository_1_1geo__located__ts__file__repository.html", null ],
    [ "shyft::core::geo_point", "structshyft_1_1core_1_1geo__point.html", null ],
    [ "shyft::core::geo_point_ts< T >", "structshyft_1_1core_1_1geo__point__ts.html", null ],
    [ "shyft::api::GeoPointSource", "classshyft_1_1api_1_1_geo_point_source.html", [
      [ "shyft::api::PrecipitationSource", "structshyft_1_1api_1_1_precipitation_source.html", null ],
      [ "shyft::api::RadiationSource", "structshyft_1_1api_1_1_radiation_source.html", null ],
      [ "shyft::api::RelHumSource", "structshyft_1_1api_1_1_rel_hum_source.html", null ],
      [ "shyft::api::TemperatureSource", "structshyft_1_1api_1_1_temperature_source.html", null ],
      [ "shyft::api::WindSpeedSource", "structshyft_1_1api_1_1_wind_speed_source.html", null ]
    ] ],
    [ "shyft::core::idw_compliant_geo_point_ts< GPTS, TSA, TA >", "classshyft_1_1core_1_1idw__compliant__geo__point__ts.html", null ],
    [ "shyft::core::inverse_distance::idw_timeaxis< TA >", "classshyft_1_1core_1_1inverse__distance_1_1idw__timeaxis.html", null ],
    [ "shyft::core::optimizer::ifx", "structshyft_1_1core_1_1optimizer_1_1ifx.html", [
      [ "shyft::core::model_calibration::dream_fx< M >", "structshyft_1_1core_1_1model__calibration_1_1dream__fx.html", null ],
      [ "shyft::core::model_calibration::sceua_fx< M >", "structshyft_1_1core_1_1model__calibration_1_1sceua__fx.html", null ]
    ] ],
    [ "shyft::core::interpolation_parameter", "structshyft_1_1core_1_1interpolation__parameter.html", null ],
    [ "shyft::api::ITimeSeriesOfPoints", "classshyft_1_1api_1_1_i_time_series_of_points.html", [
      [ "shyft::api::GenericTs< TsRep >", "structshyft_1_1api_1_1_generic_ts.html", null ]
    ] ],
    [ "shyft::api::kirchner_cell_state_statistics< cell >", "structshyft_1_1api_1_1kirchner__cell__state__statistics.html", null ],
    [ "shyft::core::land_type_fractions", "structshyft_1_1core_1_1land__type__fractions.html", null ],
    [ "shyft::core::grf::matern_model", "structshyft_1_1core_1_1grf_1_1matern__model.html", null ],
    [ "shyft::core::pt_gs_k::null_collector", "structshyft_1_1core_1_1pt__gs__k_1_1null__collector.html", null ],
    [ "shyft::core::pt_hs_k::null_collector", "structshyft_1_1core_1_1pt__hs__k_1_1null__collector.html", null ],
    [ "shyft::core::pt_ss_k::null_collector", "structshyft_1_1core_1_1pt__ss__k_1_1null__collector.html", null ],
    [ "shyft::experimental::observation_location", "structshyft_1_1experimental_1_1observation__location.html", null ],
    [ "shyft::core::model_calibration::optimizer< M, PA, PS >", "classshyft_1_1core_1_1model__calibration_1_1optimizer.html", null ],
    [ "shyft::core::precipitation_correction::parameter", "structshyft_1_1core_1_1precipitation__correction_1_1parameter.html", null ],
    [ "shyft::core::pt_gs_k::parameter", "structshyft_1_1core_1_1pt__gs__k_1_1parameter.html", null ],
    [ "shyft::core::priestley_taylor::parameter", "structshyft_1_1core_1_1priestley__taylor_1_1parameter.html", null ],
    [ "shyft::core::inverse_distance::parameter", "structshyft_1_1core_1_1inverse__distance_1_1parameter.html", [
      [ "shyft::core::inverse_distance::precipitation_parameter", "structshyft_1_1core_1_1inverse__distance_1_1precipitation__parameter.html", null ],
      [ "shyft::core::inverse_distance::temperature_parameter", "structshyft_1_1core_1_1inverse__distance_1_1temperature__parameter.html", null ]
    ] ],
    [ "shyft::core::hbv_snow::parameter", "structshyft_1_1core_1_1hbv__snow_1_1parameter.html", null ],
    [ "shyft::core::gamma_snow::parameter", "structshyft_1_1core_1_1gamma__snow_1_1parameter.html", null ],
    [ "shyft::core::bayesian_kriging::parameter", "classshyft_1_1core_1_1bayesian__kriging_1_1parameter.html", null ],
    [ "shyft::core::pt_ss_k::parameter", "structshyft_1_1core_1_1pt__ss__k_1_1parameter.html", null ],
    [ "shyft::core::skaugen::parameter", "structshyft_1_1core_1_1skaugen_1_1parameter.html", null ],
    [ "shyft::core::actual_evapotranspiration::parameter", "structshyft_1_1core_1_1actual__evapotranspiration_1_1parameter.html", null ],
    [ "shyft::core::kirchner::parameter", "structshyft_1_1core_1_1kirchner_1_1parameter.html", null ],
    [ "shyft::core::pt_hs_k::parameter_t", "structshyft_1_1core_1_1pt__hs__k_1_1parameter__t.html", null ],
    [ "shyft::timeseries::point", "structshyft_1_1timeseries_1_1point.html", null ],
    [ "shyft::timeseries::point_timeaxis", "classshyft_1_1timeseries_1_1point__timeaxis.html", null ],
    [ "shyft::timeseries::point_timeseries< TA >", "classshyft_1_1timeseries_1_1point__timeseries.html", null ],
    [ "shyft::timeseries::point_timeseries< timeaxis >", "classshyft_1_1timeseries_1_1point__timeseries.html", null ],
    [ "shyft::core::inverse_distance::precipitation_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1precipitation__model.html", null ],
    [ "shyft::api::priestley_taylor_cell_response_statistics< cell >", "structshyft_1_1api_1_1priestley__taylor__cell__response__statistics.html", null ],
    [ "shyft::api::pt_gs_k_state_io", "structshyft_1_1api_1_1pt__gs__k__state__io.html", null ],
    [ "shyft::api::pt_ss_k_state_io", "structshyft_1_1api_1_1pt__ss__k__state__io.html", null ],
    [ "shyft::core::inverse_distance::radiation_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1radiation__model.html", null ],
    [ "shyft::core::region_environment< PS, TS, RS, HS, WS >", "structshyft_1_1core_1_1region__environment.html", null ],
    [ "shyft::experimental::region_grid", "classshyft_1_1experimental_1_1region__grid.html", null ],
    [ "shyft::core::region_model< C >", "classshyft_1_1core_1_1region__model.html", null ],
    [ "shyft::experimental::orchestration::region_orchestrator", "classshyft_1_1experimental_1_1orchestration_1_1region__orchestrator.html", null ],
    [ "shyft::core::inverse_distance::rel_hum_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1rel__hum__model.html", null ],
    [ "shyft::core::actual_evapotranspiration::response", "structshyft_1_1core_1_1actual__evapotranspiration_1_1response.html", null ],
    [ "shyft::core::pt_gs_k::response", "structshyft_1_1core_1_1pt__gs__k_1_1response.html", null ],
    [ "shyft::core::pt_ss_k::response", "structshyft_1_1core_1_1pt__ss__k_1_1response.html", null ],
    [ "shyft::core::gamma_snow::response", "structshyft_1_1core_1_1gamma__snow_1_1response.html", null ],
    [ "shyft::core::skaugen::response", "structshyft_1_1core_1_1skaugen_1_1response.html", null ],
    [ "shyft::core::hbv_snow::response", "structshyft_1_1core_1_1hbv__snow_1_1response.html", null ],
    [ "shyft::core::priestley_taylor::response", "structshyft_1_1core_1_1priestley__taylor_1_1response.html", null ],
    [ "shyft::core::kirchner::response", "structshyft_1_1core_1_1kirchner_1_1response.html", null ],
    [ "shyft::core::pt_hs_k::response_t", "structshyft_1_1core_1_1pt__hs__k_1_1response__t.html", null ],
    [ "shyft::core::inverse_distance::radiation_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1radiation__model_1_1scale__computer.html", null ],
    [ "shyft::core::inverse_distance::precipitation_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1precipitation__model_1_1scale__computer.html", null ],
    [ "shyft::core::inverse_distance::wind_speed_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1wind__speed__model_1_1scale__computer.html", null ],
    [ "shyft::core::inverse_distance::rel_hum_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1rel__hum__model_1_1scale__computer.html", null ],
    [ "shyft::core::optimizer::sceua", "classshyft_1_1core_1_1optimizer_1_1sceua.html", null ],
    [ "shyft::core::grf::semi_variogram", "classshyft_1_1core_1_1grf_1_1semi__variogram.html", null ],
    [ "shyft::timeseries::sin_fx", "classshyft_1_1timeseries_1_1sin__fx.html", null ],
    [ "shyft::api::skaugen_cell_response_statistics< cell >", "structshyft_1_1api_1_1skaugen__cell__response__statistics.html", null ],
    [ "shyft::api::skaugen_cell_state_statistics< cell >", "structshyft_1_1api_1_1skaugen__cell__state__statistics.html", null ],
    [ "shyft::core::optimizer::sort_by_value_asc< vec >", "structshyft_1_1core_1_1optimizer_1_1sort__by__value__asc.html", null ],
    [ "shyft::core::grf::spherical_model", "structshyft_1_1core_1_1grf_1_1spherical__model.html", null ],
    [ "shyft::core::kirchner::state", "structshyft_1_1core_1_1kirchner_1_1state.html", null ],
    [ "shyft::core::skaugen::state", "structshyft_1_1core_1_1skaugen_1_1state.html", null ],
    [ "shyft::core::hbv_snow::state", "structshyft_1_1core_1_1hbv__snow_1_1state.html", null ],
    [ "shyft::core::gamma_snow::state", "structshyft_1_1core_1_1gamma__snow_1_1state.html", null ],
    [ "shyft::core::pt_ss_k::state", "structshyft_1_1core_1_1pt__ss__k_1_1state.html", null ],
    [ "shyft::core::pt_gs_k::state", "structshyft_1_1core_1_1pt__gs__k_1_1state.html", null ],
    [ "shyft::core::pt_gs_k::state_collector", "structshyft_1_1core_1_1pt__gs__k_1_1state__collector.html", null ],
    [ "shyft::core::pt_hs_k::state_collector", "structshyft_1_1core_1_1pt__hs__k_1_1state__collector.html", null ],
    [ "shyft::core::pt_ss_k::state_collector", "structshyft_1_1core_1_1pt__ss__k_1_1state__collector.html", null ],
    [ "shyft::experimental::repository::state_file_repository< S >", "classshyft_1_1experimental_1_1repository_1_1state__file__repository.html", null ],
    [ "shyft::experimental::repository::state_info", "structshyft_1_1experimental_1_1repository_1_1state__info.html", null ],
    [ "shyft::core::pt_hs_k::state_t", "structshyft_1_1core_1_1pt__hs__k_1_1state__t.html", null ],
    [ "shyft::core::skaugen::statistics", "structshyft_1_1core_1_1skaugen_1_1statistics.html", null ],
    [ "shyft::core::model_calibration::target_specification< PS >", "structshyft_1_1core_1_1model__calibration_1_1target__specification.html", null ],
    [ "shyft::core::inverse_distance::temperature_gradient_scale_computer::temp_point", "structshyft_1_1core_1_1inverse__distance_1_1temperature__gradient__scale__computer_1_1temp__point.html", null ],
    [ "shyft::core::inverse_distance::temperature_default_gradient_scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1temperature__default__gradient__scale__computer.html", null ],
    [ "shyft::core::inverse_distance::temperature_gradient_scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1temperature__gradient__scale__computer.html", null ],
    [ "shyft::core::inverse_distance::temperature_model< S, D, P, G, SC >", "structshyft_1_1core_1_1inverse__distance_1_1temperature__model.html", null ],
    [ "shyft::timeseries::timeaxis", "classshyft_1_1timeseries_1_1timeaxis.html", null ],
    [ "shyft::core::kirchner::trapezoidal_average< S >", "classshyft_1_1core_1_1kirchner_1_1trapezoidal__average.html", null ],
    [ "shyft::core::model_calibration::ts_transform", "structshyft_1_1core_1_1model__calibration_1_1ts__transform.html", null ],
    [ "shyft::api::TsFactory", "structshyft_1_1api_1_1_ts_factory.html", null ],
    [ "shyft::core::utcperiod", "structshyft_1_1core_1_1utcperiod.html", null ],
    [ "shyft::core::inverse_distance::wind_speed_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1wind__speed__model.html", null ],
    [ "shyft::experimental::wkt_reader", "classshyft_1_1experimental_1_1wkt__reader.html", null ],
    [ "shyft::core::YMDhms", "structshyft_1_1core_1_1_y_m_dhms.html", null ]
];