var namespaceshyft_1_1core =
[
    [ "actual_evapotranspiration", "namespaceshyft_1_1core_1_1actual__evapotranspiration.html", "namespaceshyft_1_1core_1_1actual__evapotranspiration" ],
    [ "bayesian_kriging", "namespaceshyft_1_1core_1_1bayesian__kriging.html", "namespaceshyft_1_1core_1_1bayesian__kriging" ],
    [ "gamma_snow", "namespaceshyft_1_1core_1_1gamma__snow.html", "namespaceshyft_1_1core_1_1gamma__snow" ],
    [ "grf", "namespaceshyft_1_1core_1_1grf.html", "namespaceshyft_1_1core_1_1grf" ],
    [ "hbv_snow", "namespaceshyft_1_1core_1_1hbv__snow.html", "namespaceshyft_1_1core_1_1hbv__snow" ],
    [ "inverse_distance", "namespaceshyft_1_1core_1_1inverse__distance.html", "namespaceshyft_1_1core_1_1inverse__distance" ],
    [ "kirchner", "namespaceshyft_1_1core_1_1kirchner.html", "namespaceshyft_1_1core_1_1kirchner" ],
    [ "model_calibration", "namespaceshyft_1_1core_1_1model__calibration.html", "namespaceshyft_1_1core_1_1model__calibration" ],
    [ "optimizer", "namespaceshyft_1_1core_1_1optimizer.html", "namespaceshyft_1_1core_1_1optimizer" ],
    [ "precipitation_correction", "namespaceshyft_1_1core_1_1precipitation__correction.html", "namespaceshyft_1_1core_1_1precipitation__correction" ],
    [ "priestley_taylor", "namespaceshyft_1_1core_1_1priestley__taylor.html", "namespaceshyft_1_1core_1_1priestley__taylor" ],
    [ "pt_gs_k", "namespaceshyft_1_1core_1_1pt__gs__k.html", "namespaceshyft_1_1core_1_1pt__gs__k" ],
    [ "pt_hs_k", "namespaceshyft_1_1core_1_1pt__hs__k.html", "namespaceshyft_1_1core_1_1pt__hs__k" ],
    [ "pt_ss_k", "namespaceshyft_1_1core_1_1pt__ss__k.html", "namespaceshyft_1_1core_1_1pt__ss__k" ],
    [ "skaugen", "namespaceshyft_1_1core_1_1skaugen.html", "namespaceshyft_1_1core_1_1skaugen" ],
    [ "calendar", "structshyft_1_1core_1_1calendar.html", "structshyft_1_1core_1_1calendar" ],
    [ "cell", "structshyft_1_1core_1_1cell.html", "structshyft_1_1core_1_1cell" ],
    [ "cell_statistics", "structshyft_1_1core_1_1cell__statistics.html", null ],
    [ "environment", "structshyft_1_1core_1_1environment.html", "structshyft_1_1core_1_1environment" ],
    [ "geo_cell_data", "structshyft_1_1core_1_1geo__cell__data.html", "structshyft_1_1core_1_1geo__cell__data" ],
    [ "geo_point", "structshyft_1_1core_1_1geo__point.html", "structshyft_1_1core_1_1geo__point" ],
    [ "geo_point_ts", "structshyft_1_1core_1_1geo__point__ts.html", "structshyft_1_1core_1_1geo__point__ts" ],
    [ "idw_compliant_geo_point_ts", "classshyft_1_1core_1_1idw__compliant__geo__point__ts.html", "classshyft_1_1core_1_1idw__compliant__geo__point__ts" ],
    [ "interpolation_parameter", "structshyft_1_1core_1_1interpolation__parameter.html", "structshyft_1_1core_1_1interpolation__parameter" ],
    [ "land_type_fractions", "structshyft_1_1core_1_1land__type__fractions.html", "structshyft_1_1core_1_1land__type__fractions" ],
    [ "region_environment", "structshyft_1_1core_1_1region__environment.html", "structshyft_1_1core_1_1region__environment" ],
    [ "region_model", "classshyft_1_1core_1_1region__model.html", "classshyft_1_1core_1_1region__model" ],
    [ "utcperiod", "structshyft_1_1core_1_1utcperiod.html", "structshyft_1_1core_1_1utcperiod" ],
    [ "YMDhms", "structshyft_1_1core_1_1_y_m_dhms.html", "structshyft_1_1core_1_1_y_m_dhms" ]
];